kind: pipeline
type: kubernetes
name: hulu-project

# clone:
#   disable: true
steps:
# - name: clone
#   image: alpine/git
#   commands:
#   - git config --global http.version HTTP/1.1
#   - git clone https://github.com/StoneShiLei/HuLuProject.git .
  # - git checkout $DRONE_COMMIT

- name: docker
  image: plugins/docker
  settings:
    mirror: https://jnyis2wm.mirror.aliyuncs.com
    username:
      from_secret: username
    password:
      from_secret: password
    repo: registry-vpc.cn-shanghai.aliyuncs.com/hulu0811/whatsfordinner
    registry: registry.cn-shanghai.aliyuncs.com
    tags:
      - latest
      - ${DRONE_COMMIT}

- name: dron8s
  image: bh90210/dron8s:latest
  settings:
    yaml: ./deploy.yaml
    # variables. Must be lowercase, Usage: {{.service_name}}
    image_tag: ${DRONE_COMMIT}
    kubeconfig:
        from_secret: kubeconfig

---
kind: secret
name: username
get:
  path: docker-secret
  name: DOCKER_USERNAME

---
kind: secret
name: password
get:
  path: docker-secret
  name: DOCKER_PASSWORD

---
kind: secret
name: kubeconfig
get:
  path: kubeconfig
  name: KUBECONFIG