
export default {
    UserLogin: "/user/login",
    UserRegister: "/user/register",
    UserAuth: "/user/check",
    TypeList: "/type/list",
    TypeInfo: "/type/get",
    TypeAddOrUpdate: "/type/addOrUpdate",
    TypeRemove: "/type/remove",
    FoodList: "/food/list",
    FoodInfo: "/food/get",
    FoodAddOrUpdate: "/food/addOrUpdate",
    FoodRemove: "/food/remove",
    MenuRandom: "/menu/random",
    MenuList: "/menu/list",
    MenuInfo: "/menu/get",
    MenuAddOrUpdate: "/menu/addOrUpdate",
    MenuEnable: "/menu/enable",
    MenuRemove: "/menu/remove",
};